"""initial schema

Revision ID: a6841619a1b0
Revises: 0ef8c0dc237a
Create Date: 2026-03-01 17:48:25.328879

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "a6841619a1b0"
down_revision = '0ef8c0dc237a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.alter_column('messages', 'question',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('messages', 'response',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_messages_timestamp'), table_name='messages')
    op.add_column('users', sa.Column('role', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.create_index(op.f('ix_messages_timestamp'), 'messages', ['timestamp'], unique=False)
    op.alter_column('messages', 'response',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('messages', 'question',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###